# my.kv file code here
<MainWidget>:
    ActionBar:
        ActionView:
            use_separator: true
            ActionPrevious:
                title: 'Action'
                with_previous: True
            Action Overflow:
            ActionGroup:
                text: 'Sync'
                ActionButton:
                    text: 'Sync All'
                ActionButton:
                    text: 'Sync Todoist'
                ActionButton:
                    text: 'Sync Canvas'
